{{- if .Values.monitoring.prometheusRule }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "llm-server.fullname" . }}-alerts
spec:
  groups:
  - name: llm-server
    rules:
    - alert: HighErrorRate
      expr: |
        sum(rate(llm_requests_total{status="error"}[5m])) 
        / 
        sum(rate(llm_requests_total[5m])) > 0.1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High error rate detected
        description: Error rate is above 10% for 5 minutes

    - alert: HighLatency
      expr: |
        histogram_quantile(0.95, sum(rate(llm_request_duration_seconds_bucket[5m])) by (le)) > 2
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: 95th percentile latency is above 2 seconds

    - alert: HighGPUMemoryUsage
      expr: llm_gpu_memory_used_bytes / 1024 / 1024 / 1024 > 14
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High GPU memory usage
        description: GPU memory usage is above 14GB
{{- end }} 