apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-server.fullname" . }}-config
  labels:
    {{- include "llm-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    model_server:
      default_model: {{ .Values.modelConfig.name }}
      default_version: {{ .Values.modelConfig.version }}
      max_batch_size: {{ .Values.modelConfig.maxBatchSize }}
      max_memory: {{ .Values.modelConfig.maxMemory }} 