apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-server.fullname" . }}
  labels:
    {{- include "llm-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "llm-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "alpine:3.18"
          imagePullPolicy: IfNotPresent
          command: 
            - "/bin/sh"
            - "-c"
            - |
              apk add --no-cache netcat-openbsd
              while true; do 
                echo -e 'HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\n\r\nHello World!' | nc -l -p 8000
              done
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
