apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llm-server.fullname" . }}
  labels:
    {{- include "llm-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "llm-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llm-server.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python"]
          args: ["-m", "http.server", "8000"]
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: server-config
          configMap:
            name: {{ include "llm-server.fullname" . }}-server