apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "llm-server.fullname" . }}-models
  labels:
    {{- include "llm-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.modelStorage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.modelStorage.size }} 