apiVersion: v1
kind: Service
metadata:
  name: {{ include "llm-server.fullname" . }}
  labels:
    {{- include "llm-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    {{- include "llm-server.selectorLabels" . | nindent 4 }} 